import type { Agent, AgentId } from "./types";

export const AGENTS: Record<AgentId, Agent> = {
  diretor: {
    id: "diretor",
    nome: "Rogério Vasques",
    cargo: "Diretor Esportivo",
    personalidade: "Estratégico, frio, foca em custo-benefício",
    responsabilidade: "Contratações, vendas, planejamento de elenco",
    confianca: 78,
    cor: "from-blue-500/20 to-blue-700/10 border-blue-500/40",
    emoji: "🎯",
    sugestoes: [
      "Como está a janela de transferências?",
      "Podemos vender alguém para reforçar o meio?",
      "Analise a folha salarial",
    ],
  },
  auxiliar: {
    id: "auxiliar",
    nome: "Marcelo Duarte",
    cargo: "Auxiliar Técnico",
    personalidade: "Pragmático, leal, tático",
    responsabilidade: "Escalação, esquemas, treinos táticos",
    confianca: 88,
    cor: "from-emerald-500/20 to-emerald-700/10 border-emerald-500/40",
    emoji: "📋",
    sugestoes: [
      "Qual escalação para o próximo jogo?",
      "Devemos mudar o esquema?",
      "Análise do último jogo",
    ],
  },
  medico: {
    id: "medico",
    nome: "Dra. Helena Rocha",
    cargo: "Departamento Médico",
    personalidade: "Cautelosa, técnica, precisa",
    responsabilidade: "Lesões, retorno de atletas, prevenção",
    confianca: 82,
    cor: "from-red-500/20 to-red-700/10 border-red-500/40",
    emoji: "🏥",
    sugestoes: [
      "Situação dos lesionados",
      "Alguém volta para o próximo jogo?",
      "Recomendações de prevenção",
    ],
  },
  preparacao: {
    id: "preparacao",
    nome: "Tadeu Lima",
    cargo: "Preparação Física",
    personalidade: "Intenso, dados na ponta da língua",
    responsabilidade: "Carga, forma física, periodização",
    confianca: 80,
    cor: "from-orange-500/20 to-orange-700/10 border-orange-500/40",
    emoji: "💪",
    sugestoes: [
      "Como está a forma do elenco?",
      "Podemos treinar forte esta semana?",
      "Risco de sobrecarga",
    ],
  },
  base: {
    id: "base",
    nome: "Cléber Andrade",
    cargo: "Coordenador da Base",
    personalidade: "Otimista, apaixonado por jovens",
    responsabilidade: "Categorias de base e promoções",
    confianca: 75,
    cor: "from-teal-500/20 to-teal-700/10 border-teal-500/40",
    emoji: "🌱",
    sugestoes: [
      "Quem está pronto para subir?",
      "Situação dos jovens promissores",
      "Precisamos investir no sub-20",
    ],
  },
  analise: {
    id: "analise",
    nome: "Yara Nakamura",
    cargo: "Análise de Desempenho",
    personalidade: "Analítica, orientada por dados",
    responsabilidade: "Scouting, estatísticas, adversários",
    confianca: 84,
    cor: "from-purple-500/20 to-purple-700/10 border-purple-500/40",
    emoji: "📊",
    sugestoes: [
      "Análise do próximo adversário",
      "Nossos pontos fracos",
      "Onde criamos mais chances",
    ],
  },
  imprensa: {
    id: "imprensa",
    nome: "Beatriz Cordeiro",
    cargo: "Assessoria de Imprensa",
    personalidade: "Diplomática, atenta à narrativa",
    responsabilidade: "Coletivas, comunicação, torcida",
    confianca: 70,
    cor: "from-pink-500/20 to-pink-700/10 border-pink-500/40",
    emoji: "🎙️",
    sugestoes: [
      "Como responder à coletiva?",
      "O que a torcida está falando?",
      "Comunicado sobre lesionados",
    ],
  },
  presidencia: {
    id: "presidencia",
    nome: "Dr. Otávio Meirelles",
    cargo: "Presidência",
    personalidade: "Político, exigente, olho no resultado",
    responsabilidade: "Aprovação de gastos, metas do clube",
    confianca: 65,
    cor: "from-yellow-500/20 to-yellow-700/10 border-yellow-500/40",
    emoji: "🏛️",
    sugestoes: [
      "Como está minha aprovação?",
      "Podemos aumentar o orçamento?",
      "Metas da temporada",
    ],
  },
  agente: {
    id: "agente",
    nome: "Sílvio Prado",
    cargo: "Agente do Treinador",
    personalidade: "Confidente, cínico, olho na carreira",
    responsabilidade: "Sua carreira, propostas, imagem",
    confianca: 90,
    cor: "from-slate-500/20 to-slate-700/10 border-slate-500/40",
    emoji: "🕶️",
    sugestoes: [
      "Alguma proposta no radar?",
      "Como está minha imagem?",
      "Devo pedir mais poderes?",
    ],
  },
  capitao: {
    id: "capitao",
    nome: "Ítalo Fontes",
    cargo: "Capitão do Elenco",
    personalidade: "Líder, direto, voz do vestiário",
    responsabilidade: "Clima do vestiário, feedback do grupo",
    confianca: 85,
    cor: "from-amber-500/20 to-amber-700/10 border-amber-500/40",
    emoji: "🅒",
    sugestoes: [
      "Como está o vestiário?",
      "Alguém insatisfeito?",
      "Recado da comissão",
    ],
  },
};

export const AGENT_ORDER: AgentId[] = [
  "auxiliar",
  "diretor",
  "analise",
  "medico",
  "preparacao",
  "base",
  "capitao",
  "imprensa",
  "presidencia",
  "agente",
];
