import type { ClubState } from "./types";

export function createNewCareerState(): ClubState {
  return {
    onboarded: false,
    clube: {
      nome: "",
      treinador: "",
      divisao: "",
      pais: "",
      temporada: "",
      orcamento: 0,
      moeda: "EUR",
      moralElenco: 0,
      pressaoDiretoria: 0,
      posicaoLiga: undefined,
      pontos: undefined,
      prioridadeJanela: "indefinida",
      forma: "",
      proximoJogoDias: 0,
      proximoAdversario: "",
    },
    jogadores: [],
    lesoes: [],
    calendario: [],
    decisoes: [],
    inbox: [],
    reunioes: [],
    pendencias: [],
    chats: {
      diretor: [],
      auxiliar: [],
      medico: [],
      preparacao: [],
      base: [],
      analise: [],
      imprensa: [],
      presidencia: [],
      agente: [],
      capitao: [],
    },
    confianca: {
      diretor: 0,
      auxiliar: 0,
      medico: 0,
      preparacao: 0,
      base: 0,
      analise: 0,
      imprensa: 0,
      presidencia: 0,
      agente: 0,
      capitao: 0,
    },
    memoriasAgentes: {
      diretor: [],
      auxiliar: [],
      medico: [],
      preparacao: [],
      base: [],
      analise: [],
      imprensa: [],
      presidencia: [],
      agente: [],
      capitao: [],
    },
  };
}
