import type { ClubState, Player } from "./types";

const fonteCarreira = { nome: "Dados do save + referência pública", atualizadoEm: "2026-07-28" };

const jogadores: Player[] = [
  { id: "konate", nome: "Mamadou Konaté", pos: "GOL", idade: 30, overall: 65, potencial: 65, valorMercado: 475_000, moedaValor: "EUR", moral: 68, forma: 69, papelElenco: "Rotação", confiancaTreinador: 66, contratoAte: "2027", disponivelNoJogo: true, nacionalidades: ["França"], fonte: fonteCarreira },
  { id: "lemaitre", nome: "Nicolas Lemaître", pos: "GOL", idade: 28, overall: 68, moral: 76, forma: 78, papelElenco: "Titular", confiancaTreinador: 79, contratoAte: "2027", disponivelNoJogo: true, nacionalidades: ["França"], fonte: fonteCarreira },
  { id: "maronier", nome: "Yvann Maçon", pos: "LD", idade: 27, overall: 68, moral: 73, forma: 75, papelElenco: "Titular", confiancaTreinador: 78, contratoAte: "2027", disponivelNoJogo: true, nacionalidades: ["França"], fonte: fonteCarreira },
  { id: "junior-diaz", nome: "Junior Diaz", pos: "ZAG", idade: 23, overall: 73, potencial: 80, valorMercado: 5_000_000, moedaValor: "EUR", moral: 81, forma: 82, papelElenco: "Titular importante", confiancaTreinador: 86, contratoAte: "2029", disponivelNoJogo: true, nacionalidades: ["França"], fonte: fonteCarreira },
  { id: "monfray", nome: "Adrien Monfray", pos: "ZAG", idade: 34, overall: 70, potencial: 70, valorMercado: 525_000, moedaValor: "EUR", moral: 74, forma: 72, papelElenco: "Líder do elenco", confiancaTreinador: 84, capitao: true, contratoAte: "2030", disponivelNoJogo: true, nacionalidades: ["França"], fonte: fonteCarreira },
  { id: "diawara", nome: "S. Diawara", pos: "ZAG/LE", idade: 19, overall: 60, potencial: 73, valorMercado: 550_000, moedaValor: "EUR", moral: 72, forma: 68, papelElenco: "Promessa", confiancaTreinador: 71, jovem: true, contratoAte: "2027", disponivelNoJogo: true, fonte: fonteCarreira },
  { id: "boura", nome: "Ismaël Boura", pos: "LE/ME", idade: 24, overall: 69, potencial: 74, valorMercado: 2_000_000, moedaValor: "EUR", moral: 77, forma: 80, papelElenco: "Titular", confiancaTreinador: 82, contratoAte: "2027", disponivelNoJogo: true, nacionalidades: ["França"], fonte: fonteCarreira },
  { id: "diop", nome: "Mouhamed Diop", pos: "MC/VOL", idade: 24, overall: 66, potencial: 71, valorMercado: 1_300_000, moedaValor: "EUR", moral: 76, forma: 79, papelElenco: "Titular", confiancaTreinador: 85, contratoAte: "2028", disponivelNoJogo: true, fonte: fonteCarreira },
  { id: "mille", nome: "Antoine Mille", pos: "MC", idade: 27, overall: 68, moral: 79, forma: 81, papelElenco: "Titular", confiancaTreinador: 87, contratoAte: "2027", disponivelNoJogo: true, nacionalidades: ["França"], fonte: fonteCarreira },
  { id: "hordiienko", nome: "Danylo Hordiienko", pos: "MC", idade: 17, overall: 65, potencial: 83, valorMercado: 1_700_000, moedaValor: "EUR", moral: 84, forma: 83, papelElenco: "Joia da base", confiancaTreinador: 80, jovem: true, contratoAte: "2029", disponivelNoJogo: true, nacionalidades: ["Ucrânia"], fonte: fonteCarreira },
  { id: "ifnaoui", nome: "Yassine Ifnaoui", pos: "MD/MEI/PD", idade: 26, overall: 70, potencial: 70, moral: 78, forma: 82, papelElenco: "Titular", confiancaTreinador: 83, contratoAte: "2028", disponivelNoJogo: true, fonte: fonteCarreira },
  { id: "adeline", nome: "Martin Adeline", pos: "MEI", idade: 22, overall: 69, moral: 71, forma: 76, papelElenco: "Titular importante", confiancaTreinador: 88, lesionado: true, contratoAte: "2028", disponivelNoJogo: true, nacionalidades: ["França"], fonte: fonteCarreira },
  { id: "fatah", nome: "Amar Fatah", pos: "PE/PD", idade: 22, overall: 66, potencial: 76, valorMercado: 1_600_000, moedaValor: "EUR", moral: 74, forma: 77, papelElenco: "Rotação", confiancaTreinador: 75, contratoAte: "2027", disponivelNoJogo: true, fonte: fonteCarreira },
  { id: "bentayeb", nome: "Rafiki Saïd Bentayeb", pos: "ATA", idade: 24, overall: 69, moral: 80, forma: 84, papelElenco: "Titular", confiancaTreinador: 86, contratoAte: "2028", disponivelNoJogo: true, fonte: fonteCarreira },
  { id: "avila", nome: "Gonzalo Ávila", pos: "ATA", idade: 17, overall: 64, potencial: 82, moral: 86, forma: 80, papelElenco: "Promessa", confiancaTreinador: 77, jovem: true, contratoAte: "2029", disponivelNoJogo: true, nacionalidades: ["Argentina"], fonte: fonteCarreira },
];

export function createDemoState(): ClubState {
  const now = Date.now();
  const dia = 86_400_000;
  return {
    onboarded: false,
    clube: {
      nome: "ESTAC Troyes",
      nomeCompleto: "Espérance Sportive Troyes Aube Champagne",
      treinador: "Dante",
      divisao: "Ligue 2",
      pais: "França",
      temporada: "2026/27",
      orcamento: 8_500_000,
      moeda: "EUR",
      moralElenco: 76,
      pressaoDiretoria: 38,
      posicaoLiga: 5,
      pontos: 16,
      prioridadeJanela: "defesa",
      forma: "E V E E D",
      proximoJogoDias: 5,
      proximoAdversario: "Amiens",
      fonte: fonteCarreira,
    },
    jogadores,
    lesoes: [{ jogadorId: "adeline", descricao: "Fratura no pé direito", semanas: 12 }],
    calendario: [
      { id: "guingamp", data: new Date(now - dia * 70).toISOString(), adversario: "Guingamp", competicao: "Ligue 2", casa: true, resultado: "2-2", jogado: true },
      { id: "pau", data: new Date(now - dia * 63).toISOString(), adversario: "Pau", competicao: "Ligue 2", casa: false, resultado: "1-1", jogado: true },
      { id: "annecy", data: new Date(now - dia * 56).toISOString(), adversario: "Annecy", competicao: "Ligue 2", casa: true, resultado: "1-0", jogado: true },
      { id: "boulogne", data: new Date(now - dia * 28).toISOString(), adversario: "Boulogne", competicao: "Ligue 2", casa: true, resultado: "2-0", jogado: true },
      { id: "nantes", data: new Date(now - dia * 7).toISOString(), adversario: "Nantes", competicao: "Ligue 2", casa: true, resultado: "1-2", jogado: true },
      { id: "amiens", data: new Date(now + dia * 5).toISOString(), adversario: "Amiens", competicao: "Ligue 2", casa: true },
      { id: "red-star", data: new Date(now + dia * 12).toISOString(), adversario: "Red Star", competicao: "Ligue 2", casa: false },
    ],
    decisoes: [
      { id: "d-4231", ts: now - dia * 65, titulo: "4-2-3-1 definido como sistema base", descricao: "Dante organizou o Troyes com saída apoiada, dois volantes e Adeline atacando a área.", origem: "reunião técnica" },
      { id: "d-avila", ts: now - dia * 9, titulo: "Gonzalo Ávila contratado", descricao: "O atacante argentino de 17 anos chegou como agente livre e projeto de desenvolvimento.", origem: "diretor" },
    ],
    inbox: [
      { id: "i-medico", ts: now - dia, de: "medico", para: "auxiliar", assunto: "Adeline inicia recuperação, mas segue fora por cerca de três meses", prioridade: "alta", jogadorId: "adeline" },
      { id: "i-diretor", ts: now - dia * 2, de: "diretor", para: "agente", assunto: "Junior Diaz é o principal ativo esportivo e financeiro do elenco", prioridade: "media", jogadorId: "junior-diaz" },
      { id: "i-base", ts: now - dia * 3, de: "base", para: "auxiliar", assunto: "Hordiienko e Ávila precisam de um plano individual de minutos", prioridade: "media" },
    ],
    reunioes: [],
    pendencias: [
      { jogadorId: "adeline", tipo: "promocao", descricao: "Definir substituto tático de Adeline durante a recuperação" },
      { jogadorId: "junior-diaz", tipo: "renovacao", descricao: "Definir preço mínimo para propostas por Junior Diaz" },
      { jogadorId: "avila", tipo: "promocao", descricao: "Criar plano de desenvolvimento e minutos para Gonzalo Ávila" },
    ],
    chats: { diretor: [], auxiliar: [], medico: [], preparacao: [], base: [], analise: [], imprensa: [], presidencia: [], agente: [], capitao: [] },
    confianca: { diretor: 78, auxiliar: 88, medico: 82, preparacao: 80, base: 75, analise: 84, imprensa: 70, presidencia: 67, agente: 90, capitao: 85 },
    memoriasAgentes: {
      diretor: ["Primeira janela terminou sem contratações por atraso dos relatórios", "Junior Diaz é o ativo mais valioso"],
      auxiliar: ["4-2-3-1 é o sistema base", "Adeline está lesionado"],
      medico: ["Adeline: fratura no pé direito, previsão de três meses"],
      preparacao: ["Próximo jogo em cinco dias"],
      base: ["Hordiienko e Ávila são projetos prioritários"],
      analise: ["Troyes sofreu gols em rebotes e bolas sobradas"],
      imprensa: ["A derrota para o Nantes aumentou a cobrança"],
      presidencia: ["Objetivo: disputar a parte superior da Ligue 2"],
      agente: ["Dante está em seu primeiro trabalho como treinador"],
      capitao: ["Vestiário acredita no projeto, mas cobra reação em casa"],
    },
  };
}

export function createNewCareerState(): ClubState {
  return {
    onboarded: false,
    clube: {
      nome: "",
      treinador: "",
      divisao: "",
      pais: "",
      temporada: "",
      orcamento: 0,
      moeda: "EUR",
      moralElenco: 0,
      pressaoDiretoria: 0,
      posicaoLiga: undefined,
      pontos: undefined,
      prioridadeJanela: "indefinida",
      forma: "",
      proximoJogoDias: 0,
      proximoAdversario: "",
    },
    jogadores: [],
    lesoes: [],
    calendario: [],
    decisoes: [],
    inbox: [],
    reunioes: [],
    pendencias: [],
    chats: {
      diretor: [],
      auxiliar: [],
      medico: [],
      preparacao: [],
      base: [],
      analise: [],
      imprensa: [],
      presidencia: [],
      agente: [],
      capitao: [],
    },
    confianca: {
      diretor: 0,
      auxiliar: 0,
      medico: 0,
      preparacao: 0,
      base: 0,
      analise: 0,
      imprensa: 0,
      presidencia: 0,
      agente: 0,
      capitao: 0,
    },
    memoriasAgentes: {
      diretor: [],
      auxiliar: [],
      medico: [],
      preparacao: [],
      base: [],
      analise: [],
      imprensa: [],
      presidencia: [],
      agente: [],
      capitao: [],
    },
  };
}
